#!/bin/bash
#CURLRES="curl -sL -w '%{http_code}\n' 'http://dev-elasticsearch01.j.r4e-dev:9200/_cluster/health'"
##This script is to  monitor elasticsearch
#Reference JIRA: OPS-7138

PROGNAME=`basename $0`
VERSION="Version 1.0"

ST_OK=0
ST_WR=1
ST_CR=2
ST_UK=3

COLOR0="green"
COLOR1="yellow"
COLOR2="red"

interval=1

print_version() {
    echo "  $PROGNAME $VERSION "
    
}

print_usage() {
    echo "Arguments are missing:  USAGE: $PROGNAME -H <HOSTNAME> "

}

print_help() {
    echo ""
    echo "$PROGNAME is a Nagios plugin to monitor elasticsearch cluster status"
    echo "usage parameters."
    echo ""
    echo "$PROGNAME [-H/--host] <HOSTNAME>"
    echo ""
    echo "Options:"
    echo "  --version|-v)"
    echo "    Defines version"
    echo "  --help|-h)"
    echo "    Help..."
    echo "  --host|-H)"
    echo "    Defines hostname" 
    exit $ST_UK
}

sleep $interval
if [ -z "$1" ];then print_help;exit $ST_UK;fi

sleep $interval
while test -n "$1"; do
    case "$1" in
        --help|-h)
            print_help
            exit $ST_UK
            ;;
        --version|-v)
            print_version $PROGNAME $VERSION
            exit $ST_UK
            ;;
	--host|-H)
          HOST=$2
	    if [ -z "$2" ];then print_usage;exit $ST_UK;fi
            URL="http://$HOST:9200/_cluster/health"
            shift
            ;;
        --default)
    	   DEFAULT=YES
    	    ;;
            *)
            echo "Unknown argument: $1"
            print_help
            exit $ST_UK
            ;;
    esac
    #if [ "$#" -gt 2 ]; then shift; fi
    shift
done

CURLRES=$(curl -sL -w '%{http_code}\n' "$URL")

COLOR=$(echo $CURLRES |awk -F: '{print $3}'|cut -d, -f1| sed 's/"//g')

if [[ "$COLOR" == "green" ]]; then
echo "OK: elasticsearch status green"
exit $ST_OK;
else
if [[ "$COLOR" == "yellow" ]]; then
echo "WARNING: elasticsearch status yellow"
exit $ST_WR;
else
if [[ "$COLOR" == "red" ]]; then
echo "CRITICAL: elasticsearch status critical"
exit $ST_CR;
else
echo "UNKNOWN: no result found"
exit $ST_UK;
fi
fi
fi

